# Generated by Django 5.1.1 on 2024-10-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tag_category_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.tag'),
        ),
    ]
