from django.db import models

# Create your models here.

# I didn't add id because it is autoincremented and autogenerated to any of the classes


class Category(models.Model):
    # Here I create a Category which can be a parent or a child to itself. for example if I take mitsubishi car,
    # it will be a parent of every mitsubishi series car. so it's a recursive relationship.
    name = models.CharField(max_length=255)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def __str__(self):
        return self.name

    class Meta:
        # this will just grammatically correct the plurals. if I didn't write this it would name this Categorys, which
        # is incorrect obviously
        verbose_name_plural = "Categories"


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    # 1 product can have many categories and 1 category can be in many products. so this relationship is Many to Many.
    categories = models.ManyToManyField(Category, related_name='products')
    image = models.ImageField(upload_to='products/', null=True, blank=True)  # I upload images on "products/" endpoint

    def __str__(self):
        return self.name


