# Generated by Django 5.1.1 on 2024-10-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
